apiVersion: v1
kind: Service
metadata:
  name: fleetman-queueapp1

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queueapp1
    release: "0"

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort
